# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46883c866a3601c8f58259dbdf09da0a4283c0a05d037f12ed694ee6fb88e8331a1420375900e43dd19383e6ef551e99331a157fafe9dbedc0819d80f005c481

test:
  secret_key_base: d43cb8b155b131dbc6cc6535da1fbadfe070448a07f67ac2ecff085b197910c84bbb27a5957f44b3aa178aa11ed91876397a95c7bfc0b057faa4abb4f1df657e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
